### ISSUE TITLE
I2C powered through pull-ups when I2C_POWER_INVERTED is driven HIGH

### ISSUE THREAD

**Issue by dgriswo** [adafruit/Adafruit-Feather-ESP32-S2-PCB#1]
When I2C_POWER_INVERTED is driven HIGH, the Q1 MOSFET turns off. This is supposed to turn off external I2C power (VSENSOR).

However, the i2c pull-ups (R3 and R6) are connected to 3.3v not VSENSOR. Since Adafruit STEMMA QT sensors also contain resistors between SDA/SCL and 3v3, the i2c sensors are still powered through the pull-ups.  While the ESP32-S2 is in deep sleep, the VIN pin on the [AHT20 breakout](https://www.adafruit.com/product/4566) is 2.836v. The SDA and SCL lines are both at 3.147v.

Same behavior is seen on the [LTR390 breakout](https://www.adafruit.com/product/4831)

https://forums.adafruit.com/viewtopic.php?f=57&t=187298

**Comment by ladyada** [comment]
yes this is going to be fixed in next PCB rev - we'll have a fully separate LDO!

**Comment by dgriswo** [comment]
Are you planning to connect the onboard pull-ups to the LDO output?  The mosfet is doing it's job in the current design, just some leakage through the pull-ups.

**Comment by ladyada** [comment]
yes the pullups would be also controlled by the LDO. we didn't do that here because we thought folks would want to access the lipo monitor w/o the i2c but turns out... ya cant :D

**Comment by ladyada** [comment]
done in rev C

**Comment by GizmoGoody** [comment]
@ladyada I ordered this board (without the integrated BME280 since I didn't realize that was an option) on 4/12. How can I tell if its a Rev B or C board?

**Comment by ladyada** [comment]
look on the bottom of the PCB for a letter in a circle
