### ISSUE TITLE
Adafruit Feather ESP32-S2 Pinout.pdf : error in Stemma VSENSOR signal sources

### ISSUE THREAD

**Issue by mew-cx** [adafruit/Adafruit-Feather-ESP32-S2-PCB#2]
On the Stemma connector detail of the PrettyPins diagram, there appears to be an error in the available signal sources for the power pin, see the signals highlighted below:

![stemma_vsensor_error](https://user-images.githubusercontent.com/1646418/161505560-0dd2a987-9d99-4f2e-9900-723f8f78b782.png)

The Stemma power pin is only connected to the  VSENSOR signal; it is not possible to route those other signals, so they should be deleted for clarity.

Sorry for not providing a PR, but I don't have the knowledge or toolchain for generating PrettyPins diagrams.

**Comment by kattni** [comment]
Thank you for the suggestion! PrettyPins files have been updated, both here and in the guide.
