### ISSUE TITLE
Com port changes while trying to upload Arduino sketch

### ISSUE THREAD

**Issue by muttstang** [adafruit/Adafruit-Feather-ESP32-S2-PCB#3]
I purchased the Feather ESP32-S2 with BME680 recently and it worked well for a few hours of uploading and editing code with the Arduino 2.0.3 IDE.  Then it started to throw errors when trying to upload.  

It was initially on com12 when I started using it and started switching over to com8 while trying to upload the sketch.  If I try uploading on com8 then I get this error:
`WARNING: ESP32-S2FNR2 chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this note, set --after option to 'no_reset'.
Upload error: Failed uploading: uploading error: exit status 1`

if I press reset at this point it switches over to FTHRS2BOOT and com8 goes away in the device manager.

If I try to upload on com12 (when it's available) then I get this:

`Sketch uses 615602 bytes (46%) of program storage space. Maximum is 1310720 bytes.
Global variables use 42216 bytes (12%) of dynamic memory, leaving 285464 bytes for local variables. Maximum is 327680 bytes.
Couldn't find a Board on the selected port. Check that you have the correct port selected.  If it is correct, try pressing the board's reset button after initiating the upload.`

The sketch I'm using throws this error from time to time but it didn't seem to bother it while the board was working

`C:\Users\aerejb\Documents\Arduino\libraries\Adafruit_SSD1327\Adafruit_SSD1327.cpp: In member function 'virtual void Adafruit_SSD1327::display()':
C:\Users\aerejb\Documents\Arduino\libraries\Adafruit_SSD1327\Adafruit_SSD1327.cpp:269:57: warning: narrowing conversion of 'first_row' from 'int16_t' {aka 'short int'} to 'uint8_t' {aka 'unsigned char'} inside { } [-Wnarrowing]
                    SSD1327_SETCOLUMN, row_start, row_end};
                                                         ^
C:\Users\aerejb\Documents\Arduino\libraries\Adafruit_SSD1327\Adafruit_SSD1327.cpp:269:57: warning: narrowing conversion of 'last_row' from 'int16_t' {aka 'short int'} to 'uint8_t' {aka 'unsigned char'} inside { } [-Wnarrowing]
C:\Users\aerejb\Documents\Arduino\libraries\Adafruit_SSD1327\Adafruit_SSD1327.cpp:269:57: warning: narrowing conversion of 'row_start' from 'int16_t' {aka 'short int'} to 'uint8_t' {aka 'unsigned char'} inside { } [-Wnarrowing]
C:\Users\aerejb\Documents\Arduino\libraries\Adafruit_SSD1327\Adafruit_SSD1327.cpp:269:57: warning: narrowing conversion of 'row_end' from 'int16_t' {aka 'short int'} to 'uint8_t' {aka 'unsigned char'} inside { } [-Wnarrowing]
`

I have tried the factory reset https://learn.adafruit.com/adafruit-esp32-s2-feather/factory-reset
I've tried resetting the UF2 file and that gets com12 back but it goes away when I try to upload the sketch.

I don't know if something is wrong with the board, or something changed in my arduino IDE settings but it is quite frustrating.

**Comment by ladyada** [comment]
probably your sketch is crashing and killing the USB thread. for help you can post to forums or discord - this repo is for the PCB file
